Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -14,37 +14,38 @@ on:
 jobs:      
   scan_and_lint:
     name: Scan and Lint Docker Image
-    runs-on: ubuntu-latest
-    permissions:
-      contents: read
-      packages: read
-      actions: write
-    steps:
-      - name: Checkout Repository Code
-        uses: actions/checkout@v4
-        # https://github.com/actions/checkout
-        # with:  
-        #   repository: ${{ github.repository }}
-          # ref: ${{ github.ref }}
-          # ssh-strict: true
-          # ssh-user: git
-          # persist-credentials: false
-          # fetch-depth: 0
-          # fetch-tags: true
-          # show-progress: true
-          # github-server-url: https://github.com
-      - name: find path to workflow
-        run: |
-          echo "Workflow Path: $GITHUB_WORKFLOW"
-          echo "PWD Path: $PWD"
-          echo " Full path to image-linter-and-security-scan.yml is: $(find $PWD -name image-linter-and-security-scan.yml)"
-      - name: scan_and_lint
-        uses: ./home/runner/work/Custom_RabbitMQ_Docker/Custom_RabbitMQ_Docker/.github/workflows/image-linter-and-security-scan.yml
-      - name: failure check
-        if: failure() || cancelled()
-        shell: bash
-        run: |
-          exit 1
+    uses: ./.github/workflows/image-linter-and-security-scan.yml
+    # permissions:
+    #   contents: read
+    #   packages: read
+    #   actions: write
+
+    # steps:
+    #   - name: Checkout Repository Code
+    #     uses: actions/checkout@v4
+    #     # https://github.com/actions/checkout
+    #     # with:  
+    #     #   repository: ${{ github.repository }}
+    #       # ref: ${{ github.ref }}
+    #       # ssh-strict: true
+    #       # ssh-user: git
+    #       # persist-credentials: false
+    #       # fetch-depth: 0
+    #       # fetch-tags: true
+    #       # show-progress: true
+    #       # github-server-url: https://github.com
+    #   - name: find path to workflow
+    #     run: |
+    #       echo "Workflow Path: $GITHUB_WORKFLOW"
+    #       echo "PWD Path: $PWD"
+    #       echo " Full path to image-linter-and-security-scan.yml is: $(find $PWD -name image-linter-and-security-scan.yml)"
+    #   - name: scan_and_lint
+    #     uses: ./home/runner/work/Custom_RabbitMQ_Docker/Custom_RabbitMQ_Docker/.github/workflows/image-linter-and-security-scan.yml
+    #   - name: failure check
+    #     if: failure() || cancelled()
+    #     shell: bash
+    #     run: |
+    #       exit 1
 
   build:
     name: Build and Push Docker Image
